

version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_colegio
    restart: always
    env_file:
      - .env.mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db:
    image: postgres:15
    container_name: postgres_colegio
    restart: always
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  oracle_db:
    image: gvenzl/oracle-free:23.4
    container_name: oracle_colegio
    restart: always
    env_file:
      - .env.oracle
    ports:
      - "1521:1521"
      - "5500:5500" # Puerto para Oracle APEX/Enterprise Manager
    healthcheck:
      test: ["CMD", "sqlplus", "system/Oracle123", "@scripts/healthcheck.sql"]
      interval: 10s
      timeout: 60s
      retries: 5